version: "3.8"
services:
  docker-node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nicohnavarro
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
  
volumes:
  mongo-db: