version: "3.8"
services:
  nginx:
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  docker-node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    env_file:
      - ./.env
  
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nicohnavarro
      - MONGO_INITDB_ROOT_PASSWORD=mypassword